l10n part 1 - set up tax rates
matthewcn56/howmanybobascouldmatthaveboughtwiththemoneyhespentondomains pull request #10
Opened 2021-08-06 05:50 UTC by dtjanaka

2021-08-06 06:48 UTC, matthewcn56 requested changes
This looks really great! However, I'm getting errors from our require of our sales_tax_rates json object. Since we're just serving a static html page instead of working in a node environment, we'll need the minified files of [require.js](https://requirejs.org/) for in-browser file-loading or we'll have to change the format that we bring the .json object in, just making it into a .js file and importing It in normally.

2021-08-06 06:48 UTC, matthewcn56 commented on script.js
> +const allTaxRates = require('./sales_tax_rates.json');
Do you need to include the minified package from [require.js](https://requirejs.org/docs/api.html#jsfiles) to allow require? Or else we will have to switch to a node environment and can't just serve a static html site

2021-08-06 06:48 UTC, matthewcn56 commented on script.js
> +const allTaxRates = require('./sales_tax_rates.json');
I'm getting errors on my end from the console, stopping loading.
<img width="460" alt="Screen Shot 2021-08-05 at 11 36 44 PM" src="https://user-images.githubusercontent.com/65370631/128466997-b7a914bd-9388-4e2e-82bf-48175e09048d.png">

2021-08-06 07:08 UTC, dtjanaka commented
ah i see, i'll just make it a regular js file

2021-08-06 07:52 UTC, dtjanaka commented
ah wait the object returned is a little more complex than I remembered; i'll fix this tmrw

2021-08-07 03:20 UTC, dtjanaka commented
@matthewcn56 this should be ready to merge now, no display changes yet but it pulls the country (and state if applicable) and also gets the tax rate. You can see a live version at https://how-many-bobas.uc.r.appspot.com/ in the console.

2021-08-10 00:56 UTC, matthewcn56 approved these changes
Looks great! Now it properly loads in even if location services are disabled as well

2021-08-10 04:58 UTC, merged